export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST'
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS'
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE'
export const USER_DATA_CLEAN_UP = 'USER_DATA_CLEAN_UP'

export const LOGIN_WITH_JWT_REQUEST = 'LOGIN_WITH_JWT_REQUEST'
export const LOGIN_WITH_JWT_SUCCESS = 'LOGIN_WITH_JWT_SUCCESS'
export const LOGIN_WITH_JWT_FAILURE = 'LOGIN_WITH_JWT_FAILURE'
export const LOGIN_CLEAN_UP = 'LOGIN_CLEAN_UP'

export const SINGUP_USER_REQUEST = 'SINGUP_USER_REQUEST'
export const SINGUP_USER_SUCCESS = 'SINGUP_USER_SUCCESS'
export const SINGUP_USER_FAILURE = 'SINGUP_USER_FAILURE'
export const SINGUP_CLEAN_UP = 'SINGUP_CLEAN_UP'

export const SET_JWT_TOKENS = 'SET_JWT_TOKENS'
export const SET_USER_ID = 'SET_USER_ID'

export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGOUT_CLEAN_UP = 'LOGOUT_CLEAN_UP'

export const REFRESH_ACCESS_TOKEN_REQUEST = 'REFRESH_ACCESS_TOKEN_REQUEST'
export const REFRESH_ACCESS_TOKEN_SUCCESS = 'REFRESH_ACCESS_TOKEN_SUCCESS'
export const REFRESH_ACCESS_TOKEN_FAILURE = 'REFRESH_ACCESS_TOKEN_FAILURE'

export const RESET_ROUTER_STATE = 'RESET_ROUTER_STATE'

export const HANDLE_APP_HEADER = 'HANDLE_APP_HEADER'
export const HANDLE_ACTIVE_TAB = 'HANDLE_ACTIVE_TAB'
export const SET_ACTIVE_DIALOG = 'SET_ACTIVE_DIALOG'
export const SET_ACTIVE_GROUP = 'SET_ACTIVE_GROUP'

export const WEBSOCKET_CONNECT_REQUEST = 'WEBSOCKET_CONNECT_REQUEST'
export const WEBSOCKET_CONNECT_SUCCESS = 'WEBSOCKET_CONNECT_SUCCESS'
export const WEBSOCKET_CONNECT_FAILURE = 'WEBSOCKET_CONNECT_FAILURE'

export const WEBSOCKET_SEND_REQUEST = 'WEBSOCKET_SEND_REQUEST'
export const WEBSOCKET_SEND_SUCCESS = 'WEBSOCKET_SEND_SUCCESS'
export const WEBSOCKET_SEND_FAILURE = 'WEBSOCKET_SEND_FAILURE'
export const WEBSOCKET_CLEAN_UP = 'WEBSOCKET_CLEAN_UP'

export const WEBSOCKET_RECEIVE_MESSAGE = 'WEBSOCKET_RECEIVE_MESSAGE'

export const GET_DIALOGS_REQUEST = 'GET_DIALOGS_REQUEST'
export const GET_DIALOGS_SUCCESS = 'GET_DIALOGS_SUCCESS'
export const GET_DIALOGS_FAILURE = 'GET_DIALOGS_FAILURE'
export const SET_DIALOGS_DATA = 'SET_DIALOGS_DATA'
export const SET_DIALOG_DATA = 'SET_DIALOG_DATA'
export const DIALOG_CLEAN_UP = 'DIALOG_CLEAN_UP'

export const PUSH_RECEIVE_MESSAGE_IN_DIALOG = 'PUSH_RECEIVE_MESSAGE_IN_DIALOG'
export const DELETE_DIALOG_MESSAGE = 'DELETE_DIALOG_MESSAGE'
export const UPDATE_DIALOG_MESSAGE = 'UPDATE_DIALOG_MESSAGE'
export const PUSH_NEW_DIALOG = 'PUSH_NEW_DIALOG'
export const POP_DIALOG = 'POP_DIALOG'
export const SET_AS_READ_DIALOG_MESSAGE = 'SET_AS_READ_DIALOG_MESSAGE'

export const GET_GROUPS_REQUEST = 'GET_GROUPS_REQUEST'
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS'
export const GET_GROUPS_FAILURE = 'GET_GROUPS_FAILURE'
export const SET_GROUPS_DATA = 'SET_GROUPS_DATA'
export const SET_GROUP_DATA = 'SET_GROUP_DATA'
export const GROUP_CLEAN_UP = 'GROUP_CLEAN_UP'

export const PUSH_RECEIVE_MESSAGE_IN_GROUP = 'PUSH_RECEIVE_MESSAGE_IN_GROUP'
export const DELETE_GROUP_MESSAGE = 'DELETE_GROUP_MESSAGE'
export const UPDATE_GROUP_MESSAGE = 'UPDATE_GROUP_MESSAGE'
export const PUSH_NEW_GROUP = 'PUSH_NEW_GROUP'
export const POP_GROUP = 'POP_GROUP'
export const SET_AS_READ_GROUP_MESSAGE = 'SET_AS_READ_GROUP_MESSAGE'