export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST'
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS'
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE'

export const LOGIN_WITH_JWT_REQUEST = 'LOGIN_WITH_JWT_REQUEST'
export const LOGIN_WITH_JWT_SUCCESS = 'LOGIN_WITH_JWT_SUCCESS'
export const LOGIN_WITH_JWT_FAILURE = 'LOGIN_WITH_JWT_FAILURE'

export const SINGUP_USER_REQUEST = 'SINGUP_USER_REQUEST'
export const SINGUP_USER_SUCCESS = 'SINGUP_USER_SUCCESS'
export const SINGUP_USER_FAILURE = 'SINGUP_USER_FAILURE'

export const SET_JWT_TOKENS = 'SET_JWT_TOKENS'
export const SET_USER_ID = 'SET_USER_ID'

export const REFRESH_ACCESS_TOKEN_REQUEST = 'REFRESH_ACCESS_TOKEN_REQUEST'
export const REFRESH_ACCESS_TOKEN_SUCCESS = 'REFRESH_ACCESS_TOKEN_SUCCESS'
export const REFRESH_ACCESS_TOKEN_FAILURE = 'REFRESH_ACCESS_TOKEN_FAILURE'

export const LOGOUT_USER = 'LOGOUT_USER'


export const HANDLE_APP_HEADER = 'HANDLE_APP_HEADER'

export const HANDLE_ACTIVE_TAB = 'HANDLE_ACTIVE_TAB'

export const SET_ACTIVE_DIALOG = 'SET_ACTIVE_DIALOG'

export const GET_DIALOGS_REQUEST = 'GET_DIALOGS_REQUEST'
export const GET_DIALOGS_SUCCESS = 'GET_DIALOGS_SUCCESS'
export const GET_DIALOGS_FAILURE = 'GET_DIALOGS_FAILURE'

export const GET_MESSAGES_IN_DIALOG_REQUEST = 'GET_MESSAGES_IN_DIALOG_REQUEST'
export const GET_MESSAGES_IN_DIALOG_SUCCESS = 'GET_MESSAGES_IN_DIALOG_SUCCESS'
export const GET_MESSAGES_IN_DIALOG_FAILURE = 'GET_MESSAGES_IN_DIALOG_FAILURE'
