export const AUTHENTICATE = 'authenticate'

export const DIALOGS_LIST = 'dialogs.list'
export const DIALOG_GET = 'dialog.get'
export const DIALOG_CREATE = 'dialog.create'
export const DIALOG_DELETE = 'dialog.delete'
export const DIALOG_SEND = 'dialog.message.send'
export const DIALOG_DELETE_MESSAGE = 'dialog.message.delete'
export const DIALOG_UPDATE_MESSAGE = 'dialog.message.update'
export const DIALOG_MESSAGES_SETASREAD = 'dialog.messages.setasread'
export const DIALOG_MESSAGE_STAR = 'dialog.message.star'

export const GROUPS_LIST = 'groups.list'
export const GROUP_GET = 'group.get'
export const GROUP_CREATE = 'group.create'
export const GROUP_DELETE = 'group.delete'
export const GROUP_SEND = 'group.message.send'
export const GROUP_DELETE_MESSAGE = 'group.message.delete'
export const GROUP_UPDATE_MESSAGE = 'group.message.update'
export const GROUP_MESSAGES_SETASREAD = 'group.messages.setasread'
export const GROUP_MESSAGE_STAR = 'group.message.star'