# Generated by Django 2.2.3 on 2019-08-08 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '__first__'),
        ('profiles', '0004_delete_chatgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('date', models.DateField(auto_now=True, verbose_name='date of created or updated')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.ChatGroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
