# Generated by Django 2.2.3 on 2019-08-12 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('date', models.DateField(auto_now=True, verbose_name='date of created or updated')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.ChatGroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'verbose_name': 'Message in group',
                'verbose_name_plural': 'Messages in group',
            },
        ),
        migrations.CreateModel(
            name='DialogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('date', models.DateField(auto_now=True, verbose_name='date of created or updated')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.ChatGroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'verbose_name': 'Message in dialog',
                'verbose_name_plural': 'Messages in dialog',
            },
        ),
    ]
