# Generated by Django 2.2.3 on 2019-08-12 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0001_initial'),
        ('chat_messages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialogmessage',
            name='group',
        ),
        migrations.AddField(
            model_name='dialogmessage',
            name='dialog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dialogs.Dialog'),
            preserve_default=False,
        ),
    ]
