# Generated by Django 2.2.3 on 2019-08-12 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0003_auto_20190812_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_messages', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='groups.ChatGroup'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='profiles.Profile'),
        ),
    ]
