# Generated by Django 2.2.3 on 2019-08-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190812_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('M', 'Moderator'), ('S', 'Subscriber')], max_length=1, verbose_name='Role in Group'),
        ),
    ]
