# Generated by Django 2.2.3 on 2019-07-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socket_chat', '0002_auto_20190730_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(blank=True, max_length=200, null=True, verbose_name='Date of Birth'),
        ),
    ]
