# Generated by Django 2.2.3 on 2019-07-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socket_chat', '0003_auto_20190730_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Avatar'),
        ),
    ]
