# Generated by Django 2.2.3 on 2019-07-31 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socket_chat', '0004_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
