# Generated by Django 2.2.3 on 2019-08-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190807_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(related_name='memberships', to='profiles.Profile'),
        ),
    ]
