# Generated by Django 2.2.3 on 2019-08-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190807_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatGroup',
        ),
    ]
